### ISSUE TITLE
panic: interrupted system call

### ISSUE THREAD

**Issue by nathan-osman** [davecheney/gpio#21]
I ran the sample program on my Raspberry Pi model B. It worked but when I sent `SIGINT` to the application, it resulted in a panic:

    panic: EpollWait error: interrupted system call
    
    goroutine 20 [running]:
    runtime.panic(0xb1460, 0x1030e100)
            /usr/lib/go/src/pkg/runtime/panic.c:279 +0x1a0
    github.com/davecheney/gpio.func·001()
            /home/pi/go/src/github.com/davecheney/gpio/gpio_linux.go:77 +0x208
    created by github.com/davecheney/gpio.setupEpoll
            /home/pi/go/src/github.com/davecheney/gpio/gpio_linux.go:90 +0x194s

**Comment by davecheney** [comment]
Thanks for the issue report. I have some potentially bad news. This package isn't really maintained any more, I haven't looked at it in several years. However if you wanted to send a pull request to add a loop around the EpollWait call i'd be happy to look at it.

**Comment by nathan-osman** [comment]
Thanks for letting me know. I was kinda wondering (based on the revision history) if this repository was still being maintained. I've forked it and I'll see what I can do.
